import { DIFFICULTIES, type Difficulty } from "./chart";
import { backwards, loadDrawing, routeOf } from "./drawing";
import { GUIDE_STEP } from "./guide";
import { buildPath, type Path, shareEnding } from "./path";

/** The one-line drawings in public/pictures/<id>.svg, in the order they are dealt out to the charts. */
export const PICTURES = [
  "trex",
  "bicycle",
  "whale",
  "guitar",
  "stegosaurus",
  "sun",
  "cat",
  "crocodile",
  "birdcage",
  "horse",
  "sailboat",
  "swan",
  "rocket",
  "triceratops",
  "teapot",
  "brachiosaurus",
  "snail",
  "elephant",
  "eagle",
  "deer",
  "rooster",
  "rabbit",
  "pteranodon",
  "octopus",
  "butterfly",
  "fox",
  "violin",
  "owl",
  "dodo",
  "turtle",
  "giraffe",
  "gramophone",
  "penguin",
  "windmill",
  "seahorse",
  "bear",
  "piano",
  "flamingo",
  "train",
  "jellyfish",
  "camel",
  "sewing-machine",
  "peacock",
  "ferris-wheel",
  "frog",
  "emperor-penguin",
  "dog",
  "cupcake",
  "lion",
  "dolphin",
  "sheep",
  "ice-cream",
  "squirrel",
  "crab",
  "pig",
  "pineapple",
  "hedgehog",
  "goldfish",
  "duck",
  "ramen",
  "panda",
  "bee",
  "koala",
  "hamburger",
  "kangaroo",
  "otter",
  "donut",
  "zebra",
  "hamster",
  "watermelon",
  "hippo",
  "raccoon",
  "tiger",
  "parrot",
  "monkey",
  "shark",
  "cow",
  "seal",
  "pizza",
  "polar-bear",
  "strawberry",
  "dumpling",
  "wolf",
  "toucan",
  "gorilla",
  "croissant",
  "goat",
  "snake",
  "mouse",
  "taco",
  "chameleon",
  "ladybug",
  "bison",
  "sushi",
  "moose",
  "bat",
  "cheetah",
  "tteokbokki",
  "axolotl",
  "sloth",
  "pelican",
  "rhinoceros",
  "ice-pop",
  "red-panda",
  "hermit-crab",
  "beaver",
  "swordfish",
  "corn-dog",
  "llama",
  "walrus",
  "bingsu",
  "starfish",
  "quokka",
  "pancake",
  "meerkat",
  "narwhal",
  "platypus",
  "kimbap",
  "armadillo",
  "orca",
  "hummingbird",
  "manta-ray",
  "chick",
  "bubble-tea",
  "gazelle",
  "clownfish",
  "lemur",
  "fried-chicken",
  "porcupine",
  "lobster",
  "donkey",
  "onigiri",
  "hyena",
  "pufferfish",
  "foal",
  "macaron",
  "turkey",
  "snow-leopard",
  "gecko",
  "dragonfly",
  "lynx",
  "stag-beetle",
  "iguana",
  "puffin",
  "bungeoppang",
  "cicada",
  "crane",
  "waffle",
  "wombat",
  "goose",
  "popcorn",
  "kiwi",
  "pretzel",
  "shrimp-tempura",
  "cake-slice",
  "ostrich",
  "capybara",
  "pangolin",
  "warthog",
  "tapir",
  "skunk",
  "squid",
  "french-fries",
  "woodpecker",
  "husky",
  "yak",
  "cotton-candy",
  "anglerfish",
  "stork",
  "grapes",
  "water-buffalo",
  "seagull",
  "churros",
  "eel",
  "mole",
  "bibimbap",
  "grasshopper",
  "magpie",
  "pudding",
  "corgi",
  "orangutan",
  "anteater",
  "guinea-pig",
  "badger",
  "reindeer",
  "ankylosaurus",
  "kingfisher",
  "beluga",
  "fennec-fox",
  "rhinoceros-beetle",
  "parasaurolophus",
  "dachshund",
  "clam",
  "spinosaurus",
  "sugar-glider",
  "hammerhead-shark",
  "okapi",
  "hornbill",
  "ocean-sunfish",
  "frilled-lizard",
  "ferret",
  "praying-mantis",
  "sparrow",
  "spaghetti",
  "cherries",
  "gingerbread-man",
  "sandwich",
  "lollipop",
  "banana",
  "cassowary",
  "fried-egg",
  "flying-fish",
  "corn-on-the-cob",
  "peach",
  "koi",
  "mammoth",
  "saber-toothed-cat",
  "lighthouse",
  "pigeon",
  "firefly",
  "chipmunk",
  "quail",
  "avocado",
  "albatross",
  "prairie-dog",
  "nautilus",
  "lemon",
  "cobra",
  "chinchilla",
  "pachycephalosaurus",
  "carrot",
  "velociraptor",
  "gibbon",
  "whale-shark",
  "tteokkochi",
  "falcon",
  "bulldog",
  "dilophosaurus",
  "gyeranmari",
  "salamander",
  "poodle",
  "manatee",
  "mushroom",
  "toad",
  "bighorn-sheep",
  "arctic-fox",
  "apple",
  "tarsier",
  "bread-loaf",
  "mandarin-duck",
  "pear",
  "alpaca",
  "chocolate-chip-cookie",
  "swallow",
  "eomuk-skewer",
  "marmot",
  "kiwi-fruit",
  "echidna",
  "crow",
  "aardvark",
  "cockatoo",
  "possum",
  "catfish",
  "bagel",
  "egg-tart",
  "apple-pie",
  "cheese-wedge",
  "burrito",
  "pumpkin",
  "milkshake",
  "dragon-fruit",
  "baguette",
  "coconut",
  "nachos",
  "mochi",
  "sea-lion",
  "ant",
  "lionfish",
  "vulture",
  "blue-footed-booby",
  "tangerine",
  "wildebeest",
  "sundae",
  "caterpillar",
  "spring-rolls",
  "emu",
  "pomegranate",
  "red-eyed-tree-frog",
  "hotteok",
  "moth",
  "broccoli",
  "jjajangmyeon",
  "shoebill",
  "takoyaki",
  "hoopoe",
  "cinnamon-roll",
  "betta",
  "dango",
  "pug",
  "persimmon",
  "mandrill",
  "roasted-sweet-potato",
  "sea-urchin",
  "tomato",
  "kookaburra",
  "shiba-inu",
  "tasmanian-devil",
  "pheasant",
  "secretary-bird",
  "ibex",
  "dalgona",
  "mango",
  "roasted-chestnuts",
  "fortune-cookie",
  "paella",
  "gyeran-ppang",
  "kimchi",
  "songpyeon",
  "onion-rings",
  "starfruit",
  "hoppang",
  "toast",
  "dalmatian",
  "shrimp",
  "jerboa",
  "lyrebird",
  "slow-loris",
  "honey-jar",
  "gummy-bears",
  "candy-apple",
  "chamoe",
  "lychee",
  "croquette",
  "beagle",
  "roadrunner",
  "angelfish",
  "dung-beetle",
  "stoat",
  "sea-anemone",
  "tiramisu",
  "blueberries",
  "fig",
  "udon",
  "hamburger-steak",
  "patbingsu-cup",
  "condor",
  "robin",
  "cardinal",
  "canary",
  "cockatiel",
  "heron",
  "saint-bernard",
  "brownie",
  "hare",
  "crepe",
  "gharial",
  "curry-rice",
  "blue-jay",
  "tonkatsu",
  "wolverine",
  "pho",
  "piranha",
  "fried-rice",
  "salmon",
  "serval",
  "oyster",
  "caracal",
  "maned-wolf",
  "coyote",
] as const;

export type Sewing = { readonly pictureName: string; readonly path: Path };

/**
 * The picture for one chart, and the road that sews it. The pictures are dealt out like cards to the charts,
 * in the order the songs are listed (`songNumber` counts from 0, of `songCount` songs), so no two charts sew
 * the same picture while there are enough pictures. A chart that is dealt more than one picture, and every
 * chart for the two ends a line can be sewn from, takes the one whose picture its last note completes, and
 * among those what its rhythm follows most closely, so that the bends its notes force on the road fall where the
 * picture bends anyway.
 */
export async function sewingFor(
  times: readonly number[],
  songNumber: number,
  songCount: number,
  difficulty: Difficulty,
): Promise<Sewing> {
  const turn = songNumber * DIFFICULTIES.length + DIFFICULTIES.indexOf(difficulty);
  const dealt = PICTURES.filter((_, i) => i % (songCount * DIFFICULTIES.length) === turn);
  const offered = dealt.length > 0 ? dealt : [PICTURES[turn % PICTURES.length] ?? PICTURES[0]];
  const drawings = await Promise.all(offered.map(loadDrawing));
  const sewings = drawings.flatMap((drawing) =>
    [routeOf(drawing), backwards(routeOf(drawing))].map((route) => ({
      pictureName: drawing.name,
      path: buildPath(times, route),
    })),
  );
  const best = sewings.reduce((chosen, sewing) => {
    const [fit, chosenFit] = [leftover(sewing.path), leftover(chosen.path)];
    if (fit !== chosenFit) return fit < chosenFit ? sewing : chosen;
    return sewing.path.drift < chosen.path.drift ? sewing : chosen;
  });
  return { ...best, path: shareEnding(best.path) };
}

/**
 * How badly the road misses finishing its picture on the last note: the notes left at the end with nothing to
 * draw, plus the road units of picture left undrawn. 0 when the last note completes the picture.
 */
function leftover({ anchors, guide }: Path): number {
  const spare = anchors.filter((anchor) => anchor === guide.endIndex).length - 1;
  const undrawn = guide.endIndex - (anchors[anchors.length - 1] ?? 0);
  return Math.max(0, spare) + Math.round(undrawn * GUIDE_STEP);
}
